2019-01-03 00:05:18,407 ERROR: Exception on /index [GET] [in c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\routes.py", line 34, in index
    posts = followed_posts().paginate(
NameError: name 'followed_posts' is not defined
2019-01-03 00:05:37,112 ERROR: Exception on /index [GET] [in c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\routes.py", line 34, in index
    page = request.args.get("page", 1, type=int)
NameError: name 'followed_posts' is not defined
2019-01-03 00:05:37,874 ERROR: Exception on /index [GET] [in c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\routes.py", line 34, in index
    page = request.args.get("page", 1, type=int)
NameError: name 'followed_posts' is not defined
2019-01-03 00:05:38,102 ERROR: Exception on /index [GET] [in c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\routes.py", line 34, in index
    page = request.args.get("page", 1, type=int)
NameError: name 'followed_posts' is not defined
2019-01-03 00:05:50,574 INFO: Flask_Demo startup [in C:\Users\Simon Okello\Documents\ANDELA\Flask\app\__init__.py:46]
2019-01-03 00:35:52,762 INFO: Flask_Demo startup [in C:\Users\Simon Okello\Documents\ANDELA\Flask\app\__init__.py:48]
2019-01-03 00:35:55,245 ERROR: Exception on / [GET] [in c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\routes.py", line 41, in index
    return render_template("index.html", title="Home", form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\templates\index.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\templates\layout.html", line 1, in top-level template code
    {% extends "bootstrap/layout.html" %}
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/layout.html
