2018-12-30 16:08:50,426 ERROR: Exception on /login [GET] [in c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\routes.py", line 73, in login
    return render_template("login.html", title="Sign In", form=form)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\templates\login.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\templates\layout.html", line 19, in top-level template code
    <a href="{{ url_for('explore') }}">Explore</a>
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore'. Did you mean 'edit_profile' instead?
2018-12-30 16:10:25,356 INFO: Flask_Demo startup [in C:\Users\Simon Okello\Documents\ANDELA\Flask\app\__init__.py:45]
2018-12-30 16:10:27,011 ERROR: Exception on /login [GET] [in c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\routes.py", line 73, in login
    return render_template("login.html", title="Sign In", form=form)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\templates\login.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "C:\Users\Simon Okello\Documents\ANDELA\Flask\app\templates\layout.html", line 19, in top-level template code
    <a href="{{ url_for('explore') }}">Explore</a>
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\simon okello\documents\andela\flask\env\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore'. Did you mean 'edit_profile' instead?
2018-12-30 16:17:17,570 INFO: Flask_Demo startup [in C:\Users\Simon Okello\Documents\ANDELA\Flask\app\__init__.py:45]
